on:
  pull_request:
    branches:
      - main
    types:
      - closed
      - opened
      - synchronize
    

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs: 
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Bump version and push tag
      id: versioning
      uses: anothrNick/github-tag-action@1.64.0
      env:
        WITH_V: true
        DEFAULT_BUMP: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 0.0.62-build.33
        PRERELEASE: true
        PRERELEASE_SUFFIX: build
        VERBOSE: true
        
    
    - run: >
        echo New version: ${{ steps.versioning.outputs.new_tag  }};

    - name: Build package
      run: echo 'Building package...'
      
    # - name: Create release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     tag: ${{ steps.versioning.outputs.new_tag }}
    #   run: |
    #     gh release create "$tag" \
    #         --repo="$GITHUB_REPOSITORY" \
    #         --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
    #         --generate-notes
